<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.823" timestamp="2024-09-12T16:26:34.405495+08:00" hostname="EISSENHUAN-NBVR"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\main.py", line 336, in _main
    config.hook.pytest_collection(session=session)
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\logging.py", line 790, in pytest_collection
    return (yield)
            ^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\warnings.py", line 121, in pytest_collection
    return (yield)
            ^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\config\__init__.py", line 1417, in pytest_collection
    return (yield)
            ^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\main.py", line 347, in pytest_collection
    session.perform_collect()
  File "D:\pytestAutoUI\venv\Lib\site-packages\_pytest\main.py", line 811, in perform_collect
    self.config.pluginmanager.check_pending()
  File "D:\pytestAutoUI\venv\Lib\site-packages\pluggy\_manager.py", line 391, in check_pending
    raise PluginValidationError(
pluggy._manager.PluginValidationError: unknown hook 'pytest_html_result_table_header' in plugin &lt;module 'conftest' from 'D:\\pytestAutoUI\\conftest.py'&gt;</error></testcase></testsuite></testsuites>