<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="10.854" timestamp="2024-10-06T01:12:05.161007+08:00" hostname="EISSENHUAN-NBVR"><testcase classname="test_dir.test_parametrize" name="test_baidu_search[1-selenium]" time="9.139"><error message="failed on setup with &quot;AttributeError: 'list' object has no attribute 'items'&quot;">cls = &lt;class '_pytest.runner.CallInfo'&gt;, func = &lt;function call_and_report.&lt;locals&gt;.&lt;lambda&gt; at 0x0000020DE28A3C40&gt;
when = 'setup', reraise = (&lt;class '_pytest.outcomes.Exit'&gt;, &lt;class 'KeyboardInterrupt'&gt;)

    @classmethod
    def from_call(
        cls,
        func: Callable[[], TResult],
        when: Literal["collect", "setup", "call", "teardown"],
        reraise: type[BaseException] | tuple[type[BaseException], ...] | None = None,
    ) -&gt; CallInfo[TResult]:
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :type func: Callable[[], _pytest.runner.TResult]
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
&gt;           result: TResult | None = func()

C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:242: in &lt;lambda&gt;
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\_hooks.py:513: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:90: in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:70: in unraisable_exception_runtest_hook
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\logging.py:842: in pytest_runtest_setup
    yield from self._runtest_for(item, "setup")
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\logging.py:831: in _runtest_for
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\capture.py:874: in pytest_runtest_setup
    return (yield)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\threadexception.py:87: in pytest_runtest_setup
    yield from thread_exception_runtest_hook()
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\threadexception.py:68: in thread_exception_runtest_hook
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:160: in pytest_runtest_setup
    item.session._setupstate.setup(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;_pytest.runner.SetupState object at 0x0000020DE1A4B7D0&gt;, item = &lt;Function test_baidu_search[1-selenium]&gt;

    def setup(self, item: Item) -&gt; None:
        """Setup objects along the collector chain to the item."""
        needed_collectors = item.listchain()
    
        # If a collector fails its setup, fail its entire subtree of items.
        # The setup is not retried for each item - the same exception is used.
&gt;       for col, (finalizers, exc) in self.stack.items():
E       AttributeError: 'list' object has no attribute 'items'

C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:504: AttributeError</error></testcase><testcase classname="test_dir.test_parametrize" name="test_baidu_search[2-poium]" time="0.001"><error message="failed on setup with &quot;AttributeError: 'list' object has no attribute 'items'&quot;">cls = &lt;class '_pytest.runner.CallInfo'&gt;, func = &lt;function call_and_report.&lt;locals&gt;.&lt;lambda&gt; at 0x0000020DE2EC5260&gt;
when = 'setup', reraise = (&lt;class '_pytest.outcomes.Exit'&gt;, &lt;class 'KeyboardInterrupt'&gt;)

    @classmethod
    def from_call(
        cls,
        func: Callable[[], TResult],
        when: Literal["collect", "setup", "call", "teardown"],
        reraise: type[BaseException] | tuple[type[BaseException], ...] | None = None,
    ) -&gt; CallInfo[TResult]:
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :type func: Callable[[], _pytest.runner.TResult]
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
&gt;           result: TResult | None = func()

C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:242: in &lt;lambda&gt;
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\_hooks.py:513: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pluggy\_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:90: in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\unraisableexception.py:70: in unraisable_exception_runtest_hook
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\logging.py:842: in pytest_runtest_setup
    yield from self._runtest_for(item, "setup")
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\logging.py:831: in _runtest_for
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\capture.py:874: in pytest_runtest_setup
    return (yield)
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\threadexception.py:87: in pytest_runtest_setup
    yield from thread_exception_runtest_hook()
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\threadexception.py:68: in thread_exception_runtest_hook
    yield
C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:160: in pytest_runtest_setup
    item.session._setupstate.setup(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;_pytest.runner.SetupState object at 0x0000020DE1A4B7D0&gt;, item = &lt;Function test_baidu_search[2-poium]&gt;

    def setup(self, item: Item) -&gt; None:
        """Setup objects along the collector chain to the item."""
        needed_collectors = item.listchain()
    
        # If a collector fails its setup, fail its entire subtree of items.
        # The setup is not retried for each item - the same exception is used.
&gt;       for col, (finalizers, exc) in self.stack.items():
E       AttributeError: 'list' object has no attribute 'items'

C:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\runner.py:504: AttributeError</error></testcase></testsuite></testsuites>